version: "3"

services:
  ray-head:
    image: rayproject/ray:latest-py310-cpu
    ports:
      - "${REDISPORT}:${REDISPORT}"
      - "${DASHBOARDPORT}:${DASHBOARDPORT}"
      - "${HEADNODEPORT}:${HEADNODEPORT}"
    env_file:
      - .env
    command: bash -c "ray start --head --dashboard-port=${DASHBOARDPORT} --port=${REDISPORT} --dashboard-host=0.0.0.0 --redis-password=${REDISPASSWORD} --block"
    shm_size: 2g
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'


  ray-worker:
    image: rayproject/ray:latest-py310-cpu
    depends_on: 
      - ray-head
    env_file:
      - .env
    command: bash -c "ray start --address=ray-head:${REDISPORT} --redis-password=${REDISPASSWORD} --num-cpus=${NUM_CPU_WORKER} --block" 
    shm_size: 2g
    deploy:
      mode: replicated
      replicas: ${NUM_WORKERS} 
      resources:
        limits:
          cpus: ${NUM_CPU_WORKER}
          memory: '2g'


  main:
    image: python:3.10-bookworm
    ports:
    - 8888:8888
    volumes:
    - ./main:/app
    environment:
    - RAY_ADDRESS=ray-head:${REDISPORT}
    working_dir: /app
    command: ["./docker-entrypoint.sh"]